### ISSUE TITLE
dompdf_fonts and smarty 5

### ISSUE THREAD

**Issue by destrieux** [eileenmcnaughton/dompdf-fonts#2]
Hi Eilen, 
I cannot run dompdf_fonts with smarty 5 : I get a wordpress fatal error and the following logs
I tried to use the master branch wo success
thanks for your help 
best

------
[23-Sep-2024 18:27:31 Europe/Paris] PHP Fatal error:  Uncaught Error: Cannot access protected property Smarty\Smarty::$template_dir in /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php:26
Stack trace:
#0 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/ext/dompdf-fonts-master/dompdf_fonts.civix.php(99): Smarty->__get('template_dir')
#1 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/ext/dompdf-fonts-master/dompdf_fonts.civix.php(129): _dompdf_fonts_civix_civicrm_config()
#2 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/ext/dompdf-fonts-master/dompdf_fonts.php(32): _dompdf_fonts_civix_civicrm_install()
#3 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(71): dompdf_fonts_civicrm_install()
#4 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(39): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), 'install')
#5 /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/ in /Applications/MAMP/htdocs/29/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php on line 26

**Comment by eileenmcnaughton** [comment]
I ran `civix upgrade` - should be fixed if you grab the latest now

**Comment by destrieux** [comment]
Many thanks !
